brad_dong/week5/Wdi-future-login/config/routes.rb
Rails.application.routes.draw do

  get '/login' =>'session#new'

  post '/login' => 'session#create'

  delete '/login' => 'session#destroy'

  resources :users, except: [:index]   # don't create the index action or template

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :futures

  resources :students
end

brad_dong/week5/Wdi-future-login/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

brad_dong/week5/Wdi-future-login/app/models/future.rb
class Future < ApplicationRecord
  has_many :students
end

brad_dong/week5/Wdi-future-login/app/models/student.rb
class Student < ApplicationRecord
  belongs_to :future
end

brad_dong/week5/Wdi-future-login/app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  validates :email, presence: true, uniqueness: true
end

brad_dong/week5/Wdi-future-login/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :fetch_user

  private

  def fetch_user
    if session[:user_id].present?
      @current_user = User.find_by :id =>session[:user_id]
      session[:user_id] = nil unless @current_user
    end
  end

end

brad_dong/week5/Wdi-future-login/app/controllers/futures_controller.rb
class FuturesController<ApplicationController

#create
  def new
    @future =Future.new  #create blank object for form_for helper to use
  end

  def create
    Future.create future_params
    redirect_to(futures_path)
  end

#read
  def index
    @futures = Future.all
  end

  def show
    @future = Future.find params[:id]
  end

#update
  def edit
    @future = Future.find params[:id]
  end

  def update
    @future = Future.find params[:id]
    @future.update future_params
    redirect_to future_path(@future.id)
  end

#delete
  def destroy
    future = Future.find params[:id]
    puts future
    future.destroy
    redirect_to futures_path
  end


  private

  def future_params
    params.require(:future).permit(:name, :year, :location, :image)
  end

end

brad_dong/week5/Wdi-future-login/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    #see if the email address actually corresponds to a user in the table
    user = User.find_by email: params[:email]

    if user.present? && user.authenticate( params[:password]) #if email exists and password good
      #successful login
      #get rails to create new session key to store the user's id.
      #this is the session key which we will use to check if the user is logged in on all future pages
      session[:user_id] = user.id

      redirect_to user_path(user.id)
    else
      #wrong credentials
      flash[:error] = "invalid email address or password"

      redirect_to (login_path)
    end

  end

  def destroy
    session[:user_id] = nil #this logs out the user
    redirect_to login_path
  end
end

brad_dong/week5/Wdi-future-login/app/controllers/students_controller.rb
class StudentsController < ApplicationController

  #create
    def new
      @student =Student.new  #create blank object for form_for helper to use
    end

    def create
      Student.create student_params
      redirect_to(students_path)
    end

  #read
    def index
      @students = Student.all
    end

    def show
      @student = Student.find params[:id]
    end

  #update
    def edit
      @student = Student.find params[:id]
    end

    def update
      @student = Student.find params[:id]
      @student.update student_params
      redirect_to student_path(@student.id)
    end

  #delete
    def destroy
      student = Student.find params[:id]
      student.destroy
      redirect_to students_path
    end


    private

    def student_params
      params.require(:student).permit(:name, :location, :hobbies, :image, :future_id)
    end


end

brad_dong/week5/Wdi-future-login/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user =User.create user_params

    if user.persisted?  #did the user get saved/created?
      session[:user_id]=user.id #log in the new user
      redirect_to user_path(user.id) #go to show page for this user
    else
      #account not created, show error
      flash[:errors] = user.errors.full_messages  #set  a flash key to show on the next page: it will be an array of error strings
      redirect_to new_user_path  #create new user page
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

brad_dong/week5/Wdi-future-login/app/helpers/application_helper.rb
module ApplicationHelper
end

brad_dong/week5/Wdi-future-login/app/helpers/session_helper.rb
module SessionHelper
end

brad_dong/week5/Wdi-future-login/app/helpers/users_helper.rb
module UsersHelper
end

brad_dong/week5/Wdi-future-login/app/views/students/_form.html.erb
<%= form_for @student do |f| %>

  <fieldset>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </fieldset>
  <fieldset>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </fieldset>
  <fieldset>
    <%= f.label :hobbies %>
    <%= f.text_field :hobbies %>
  </fieldset>
  <fieldset>
    <%= f.label :image %>
    <%= f.text_field :image %>
  </fieldset>

  <fieldset>
    <%= f.label :future_id, 'Class' %>
    <%= f.collection_select :future_id, Future.all, :id, :name, prompt: 'Please choose an class' %>
  </fieldset>
  <%= f.submit %>


<% end %>

brad_dong/week5/Wdi-future-login/app/views/students/edit.html.erb
<h2>Edit <%= @student.name %></h2>

<%= render partial: 'form' %>

brad_dong/week5/Wdi-future-login/app/views/students/index.html.erb
<h2>All WDI students</h2>

<ul>
  <% @students.each do|t| %>
    <li>
      <%= link_to t.name, student_path(t.id) %>
    </li>
  <% end %>
</ul>

brad_dong/week5/Wdi-future-login/app/views/students/new.html.erb
<h2>Please enter student details</h2>

<%= render partial: 'form' %>

brad_dong/week5/Wdi-future-login/app/views/students/show.html.erb
<h2>Student: <%= @student.name %></h2>

<nav>
  <%= link_to 'Edit this student', edit_student_path(@student.id) %>||
  <%= link_to 'Delete this student', student_path(@student.id), method: 'delete'%>

</nav>

<p>
  Location: <%= @student.location %><br>
  Hobbies: <%= @student.hobbies %><br>

  <%= image_tag @student.image, alt:@student.name , :class=>"image"%>

</p>